#!/usr/bin/env bash
Netconf="/etc/NetworkManager/NetworkManager.conf"
Line="==================================="
WriteChange1='sed -i -e 's/rc-manager=file/#rc-manager=file/g' /etc/NetworkManager/NetworkManager.conf'
WriteChange2='sed -i -e 's/dns=none/#dns=none/g' /etc/NetworkManager/NetworkManager.conf'

if [ $EUID -ne 0 ]
then echo "Please run as root."
  exit
fi
# Check if the file is uncommented
if grep -q -E '(^|\s)#rc-manager=file($|\s)' $Netconf && grep -q -E '(^|\s)#dns=none($|\s)' $Netconf; then
  echo $Line
  echo DNS is already turned off
elif grep -q -E '(^|\s)rc-manager=file($|\s)' $Netconf && grep -q -E '(^|\s)dns=none($|\s)' $Netconf; then
  echo Changing...
  sleep 2
  $WriteChange1
  $WriteChange2
  rm -f /etc/resolv.conf
  netconfig update -f 
  systemctl restart NetworkManager
  systemctl restart dnscrypt-proxy.socket
  echo $Line
  echo DNS turned off.
fi
