#!/usr/bin/env bash
Netconf="/etc/NetworkManager/NetworkManager.conf"
Line="==================================="
WriteChange1='sed -i -e 's/#rc-manager=file/rc-manager=file/g' /etc/NetworkManager/NetworkManager.conf'
WriteChange2='sed -i -e 's/#dns=none/dns=none/g' /etc/NetworkManager/NetworkManager.conf'

# Check if the file is commented

if [ $EUID -ne 0 ]
then echo "Please run as root."
  exit
fi

if grep -q -E '(^|\s)rc-manager=file($|\s)' $Netconf && grep -q -E '(^|\s)dns=none($|\s)' $Netconf; then
  echo $Line
  echo DNS is already on
elif grep -q -E '(^|\s)#rc-manager=file($|\s)' $Netconf && grep -q -E '(^|\s)#dns=none($|\s)' $Netconf; then
  echo Changing...
  $WriteChange1
  $WriteChange2
  systemctl restart NetworkManager
  systemctl restart dnscrypt-proxy.socket
  cp /etc/resolv.conf.bak /etc/resolv.conf
  sleep 2
  echo $Line
  echo DNS turned on
fi
